stateDiagram-v2

[*] -->Idle
Idle --> Arming : Next
Idle --> Idle : Abort

Arming --> Armed : Next
Arming --> Idle : Abort

state TripLimitCheck <<choice>>
state TripCountCheck <<choice>>
Armed --> Tripped : Next
Armed --> Idle : Abort

Tripped --> TripLimitCheck : Next
Tripped --> Idle : Abort

TripLimitCheck --> Arming: limit == 0
TripLimitCheck --> TripCountCheck: limit > 0

TripCountCheck --> Arming: count < limit
TripCountCheck --> Idle: count >= limit