classDiagram
    class TimeTriggerActions{
        <<enumeration>>
        Next
        Abort
    }
    class TimeTriggerStates{
        <<enumeration>>
        Inactive
        Armed
        Triggered
    }
    class Trigger{
        -TriggerStateIdle _stateIdle
        -TriggerStateArmed _stateArmed
        -TriggerStateTripped _stateTripped
        -TriggerStateBase _currentState

        +State() number
        +Identifier() string
        +Signature() string
        +Name() string
        +Timeout() number
        +Duration() number

        +Start()
        +Stop()

        +EnterIdle()
        +EnterArmed()
        +EnterTripped()

        -_doStart()
        -_doStop()
        -_on_timerTripped()
        -_doStateChange()
        -_generateNewTimerValues()
        -_checkRange()$
        __getNextValue()$
    }
    class TriggerStateBase{
       <<Abstract>>
       -Trigger owner
       -doNext() boolean
       -doAbort() boolean
       +constructor(Object config)
       +Name() string
       +Evaluate(TriggerActions action) boolean
       +OnEntrance()
       +OnExit()
    }
    class TriggerStateIdle{
       +constructor(Object config)
       +Name() string
       +State number
       -doNext() boolean
       -doAbort() boolean
    }
    class TriggerStateArmed{
       +constructor(Object config)
       +Name() string
       +State number
       -doNext() boolean
       -doAbort() boolean
    }
    class TriggerStateTripped{
       +constructor(Object config)
       +Name() string
       +State number
       -doNext() boolean
       -doAbort() boolean
    }
    Trigger "1" *-- TriggerStateIdle
    Trigger "1" *-- TriggerStateArmed
    Trigger "1" *-- TriggerStateTripped
    Trigger "1" o-- "1" TimeTriggerActions
    Trigger "1" o-- "1" TimeTriggerStates
    TriggerStateBase "1" o-- "1" TimeTriggerActions
    TriggerStateBase "1" o-- "1" TimeTriggerStates
    TriggerStateBase "1" o-- Trigger
    TriggerStateBase <|-- TriggerStateIdle
    TriggerStateBase <|-- TriggerStateArmed
    TriggerStateBase <|-- TriggerStateTripped
